version: "3.9"
services:
  api:
    build: backend
    stdin_open: true
    tty: true
    env_file:
      - docker-env/api.env
    ports:
      - "8000:5000"
    depends_on:
      - db
    volumes:
      - ./backend:/home/code
    command: flask run
  db:
    image: postgres:12.3-alpine
    ports:
      - 5432:5432
    env_file:
      - docker-env/db.env
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data
  # frontend:
  #   build: frontend
  #   command: npm run start
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./frontend:/usr/src/app
  #     - ./frontend/node_modules:/usr/src/app/node_modules:cached
