"""changed email field

Revision ID: f02e086ec113
Revises: ee70d9dd274d
Create Date: 2022-08-02 14:44:06.097847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02e086ec113'
down_revision = 'ee70d9dd274d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('note_email_key', 'note', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('note_email_key', 'note', ['email'])
    # ### end Alembic commands ###
